#pragma once

#define LAYER_STATE_32BIT

#define TAPPING_TOGGLE 1

#define MOUSEKEY_DELAY 1
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_MAX_SPEED 12
#define MOUSEKEY_TIME_TO_MAX 128

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD