# override default userspace
USER_NAME := h4okr/stdev-nobl

NKRO_ENABLE = yes
LTO_ENABLE = no
QMK_SETTINGS = yes
DYNAMIC_MACRO_ENABLE = yes
SEND_STRING_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = yes
MOUSEKEY_ENABLE = yes
# RGB_MATRIX_CUSTOM_USER = yes