#include QMK_KEYBOARD_H
//#include "./leds.c"
#include "./layers.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_UNIV_1] = LAYOUT(
		KC_1, 	KC_2, 	KC_3, 	KC_4, 	KC_5,   KC_6,
		KC_QUOT,KC_Q, 	KC_W, 	KC_E,   KC_R,  	KC_T, 
		KC_TAB, KC_A,   KC_S,   KC_D,   KC_F,   KC_G, 
		KC_LSFT,KC_Z,   KC_X,   KC_C,  	KC_V, 	KC_B,		
		KC_LCTL,KC_LALT,MN_FUNC,MN_MOVE,MN_2,   KC_SPC), 

	[_UNIV_2] = LAYOUT( 
	  KC_7,		KC_8,		KC_9,		KC_0,		KC_MINS,KC_EQL,  
		KC_Y,		KC_U,		KC_I,		KC_O,		KC_P,		KC_LBRC, 
		KC_H,		KC_J,		KC_K,		KC_L,		KC_SCLN,KC_RBRC, 
		_______,KC_N,		KC_M,		KC_COMM,KC_DOT,	KC_SLSH,
		_______,_______,_______,_______,_______,KC_ENT), 

	[_MOVE] = LAYOUT( 
		KC_ESC,	KC_CAPS,_______,_______,_______,_______,
		KC_NUHS,KC_BSPC,KC_UP,	KC_DEL,	_______,_______, 
		_______,KC_LEFT,KC_DOWN,KC_RGHT,KC_PGUP,_______, 
		_______,KC_NUBS,KC_HOME,KC_END, KC_PGDN,_______, 
		_______,_______,_______,_______,_______,_______), 

	[_NUM] = LAYOUT( 
		MN_NUM, KC_NUM,	_______,_______,KC_PSLS,KC_PEQL, 
		KC_GRV, KC_P7,	KC_P8,	KC_P9,	KC_PAST,_______, 
		KC_CALC,KC_P4,	KC_P5,	KC_P6,	KC_PMNS,_______, 
		_______,KC_P1,	KC_P2,	KC_P3,	KC_PPLS,_______, 
		_______,KC_P0,	KC_PDOT,_______,_______,KC_PENT), 

	[_FUNCTION] = LAYOUT( 
		KC_F1,	KC_F2,	KC_F3,	KC_F4,	KC_F5,  KC_F6,
		KC_F7,	KC_F8,	KC_F9,	KC_F10,	KC_F11, KC_F12,
		KC_LGUI,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______, 
		_______,_______,_______,MN_NUM, MN_CONF,KC_PSCR), 

	[_CONFIG] = LAYOUT( 
		QK_BOOT,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,KC_WBAK,KC_VOLU,KC_WFWD,XXXXXXX,XXXXXXX, 
		XXXXXXX,KC_MPRV,KC_VOLD,KC_MNXT,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,KC_MUTE,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,MN_CONF,KC_MPLY), 

	[6] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

	[7] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

	[8] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 
};

/*

	[] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

*/