#include QMK_KEYBOARD_H
#include "./leds.c"
#include "./layers.h"

bool enable_gui = true;

enum custom_keycodes {
  MN_GUI = SAFE_RANGE,
	MNNOGUI
};




const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_UNIV_1] = LAYOUT(
		KC_ESC,	KC_1, 	KC_2, 	KC_3, 	KC_4, 	KC_5, 
		KC_GRV, KC_Q, 	KC_W, 	KC_E,   KC_R,  	KC_T, 
		KC_TAB, KC_A,   KC_S,   KC_D,   KC_F,   KC_G, 
		KC_LSFT,KC_W,   KC_X,   KC_C,  	KC_V, 	KC_B,		
		KC_LCTL,KC_LALT,MN_GUI,	MN_MOVE,MN_2,   KC_SPC), 

	[_UNIV_2] = LAYOUT( 
		KC_6,		KC_7,		KC_8,		KC_9,		KC_0,		KC_MINS, 
		KC_Y,		KC_U,		KC_I,		KC_O,		KC_P,		KC_LBRC, 
		KC_H,		KC_J,		KC_K,		KC_L,		KC_SCLN,KC_RBRC, 
		KC_N,		KC_M,		KC_COMM,KC_DOT,	KC_SLSH,KC_QUOT,
		XXXXXXX,XXXXXXX,MN_FUNC,XXXXXXX,XXXXXXX,KC_ENT), 

	[_MOVE] = LAYOUT( 
		MN_NUM,	XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,KC_EQL, 
		KC_NUHS,KC_BSPC,KC_UP,	KC_DEL,	XXXXXXX,XXXXXXX, 
		XXXXXXX,KC_LEFT,KC_DOWN,KC_RGHT,KC_PGUP,XXXXXXX, 
		XXXXXXX,KC_NUBS,KC_HOME,KC_END, KC_PGDN,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

	[_NUM] = LAYOUT( 
		MN_EXIT,KC_NUM,	XXXXXXX,XXXXXXX,KC_PSLS,KC_PEQL, 
		XXXXXXX,KC_P7,	KC_P8,	KC_P9,	KC_PAST,XXXXXXX, 
		XXXXXXX,KC_P4,	KC_P5,	KC_P6,	KC_PMNS,XXXXXXX, 
		XXXXXXX,KC_P1,	KC_P2,	KC_P3,	KC_PPLS,XXXXXXX, 
		XXXXXXX,KC_P0,	KC_PDOT,XXXXXXX,XXXXXXX,KC_PENT), 

	[_FUNCTION] = LAYOUT( 
		MN_EXIT,KC_F1,	KC_F2,	FC_F3,	KC_F4,	KC_F5, 
		KC_F6,	KC_F7,	KC_F8,	FC_F9,	KC_F10,	KC_F11, 
		KC_F12,	KC_PSCR,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,MNNOGUI,XXXXXXX,XXXXXXX,XXXXXXX), 

	[5] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

	[6] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

	[7] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

	[8] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 
};

/*

	[] = LAYOUT( 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX, 
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX), 

*/